### ISSUE TITLE
The name for BipartiteView?

### ISSUE THREAD

**Issue by spagnuolocarmine** [pszufe/SimpleHypergraphs.jl#3]
The name is fine, but we can also check if it's corresponds to Incidence Graph or Levi graph. This could be just added to the documentation.

**Comment by spagnuolocarmine** [comment]
Other information. According to:
Alain Bretto. 2013. Hypergraph Theory: An Introduction. Springer Publishing Company, Incorporated.

At page 27, the bipartite graph IG(H) of the graph H, is defined as the *incidence graph* of a hypergraph H = (V; E).

We can decide, I think that is interchangeable.

**Comment by pszufe** [comment]
Since all graph mathematicians (not even having hypergraph experience) know what *biparitite* means my proposal is to leave the `BipartiteView` name, but in each part of documentation describe it as the *incidence graph* and *Levi* graph. In this way library will be more friendly to use. Does it sound OK?

**Comment by spagnuolocarmine** [comment]
absolutely fine!
